import React,{useState}from'react';import{createRoot}from'react-dom/client';import{createPortal}from'react-dom';import{ArrowLeft,ArrowRight,Check,ChevronDown,Menu,Target,Volume2,VolumeX,X}from'lucide-react';import'./styles.css';
const A='/assets/';
const tabs=['The foundation','Right-sized plan','Timing','Six components','Exam lens'];
const components=[
['Quality Standards','08-quality-standards.png','The specific standards the project will use — authority-created standards, general consensus standards, and applicable regulations. Answers, concretely, "against what benchmark are we actually measuring quality?"'],
['Quality Objectives','09-quality-objectives.png','Specific, stated goals related to the quality of the project\'s outputs — not a vague aspiration toward "high quality," but concrete targets. Example: "Defect rate below 2% at final inspection" is a quality objective. "We want good quality" is not — it gives nobody anything to actually measure against.'],
['Roles','10-quality-roles.png','Who is actually accountable for managing quality — who owns quality assurance, who owns quality control, and who has the authority to halt work if a standard isn\'t being met. Without this named clearly, quality accountability tends to default to "everyone," which in practice means no one.'],
['Deliverables','11-quality-deliverables.png','Not every deliverable or process necessarily gets the same level of scrutiny — this specifies which ones will actually be reviewed, and which won\'t receive the same depth of check. A deliberate prioritization decision, not an oversight.'],
['QC/QM Activities','12-quality-activities.png','The planned activities for actually controlling and managing quality throughout the project — inspections, testing cadences, review cycles — mapped out in advance rather than improvised whenever someone happens to remember to check.'],
['Tools','13-quality-tools.png','The specific tools and techniques used for quality assurance and control — PDCA, root cause analysis, fishbone diagrams — alongside detailed procedures for what happens when a deliverable fails a quality check, and how continuous improvement gets built in going forward. The plan\'s written answer to: what happens when a check actually fails?']];
const modalData={
hook:{title:'Quality planning works the same way.',image:'02-quality-blueprint-modal.png',text:'The quality management plan isn\'t a document written to describe quality after the fact — it\'s the blueprint deciding, before real work begins, exactly how quality will be checked, by whom, against what standard, and what happens the moment something fails that check. This lesson walks through its six components.'},
fit:{title:'A plan sized to fit the project',image:'04-proportionality-modal.png',text:'This enabler asks the project manager to plan the quality processes and tools that make up the quality management plan — describing how policies, procedures, and guidelines will actually be implemented to achieve the project\'s quality objectives, along with the activities and resources needed to get there. PMBOK® 8 is explicit about proportionality here: this plan can be formal or informal, detailed or broadly framed. Its style and level of detail should match what the project actually requires — a small internal project doesn\'t need the same depth of formal quality documentation as a regulated medical device rollout, and forcing identical rigor onto both wastes effort on the smaller project without adding real protection.'},
timing:{title:'Timing never flexes',image:'06-timing-benefits-modal.png',text:'PMBOK® 8 is equally explicit about timing: the plan should be reviewed early in the project, so decisions rest on accurate information from the start. The named benefits of doing this early are concrete — a sharper focus on the project\'s actual value proposition, real reductions in cost, and fewer schedule overruns caused by rework. The logic is simple and worth remembering exactly as stated: quality planned late is rework scheduled. Every quality check skipped in planning becomes a defect discovered downstream, and every defect discovered downstream costs more to fix than it would have cost to prevent.'},
example:{title:'Worked example',image:'14-software-worked-example.png',text:'A software project\'s quality management plan might specify unit test coverage thresholds as a standard, "zero critical defects at release" as an objective, the QA lead as the accountable role, the checkout and payment modules as the deliverables receiving the deepest review, automated regression testing as the control activity, and a defined defect-triage process — including who re-tests a fix and how it gets re-verified — as the nonconformance procedure. Every one of the six components is present, and every one was decided before development started, not improvised once a bug was found.'},
exam:{title:'Plan Quality Processes and Tools',image:'16-exam-synthesis.png',text:'The quality management plan describes how policies, procedures, and guidelines will actually be implemented to achieve quality objectives — sized to fit the project, whether that means formal and detailed or lighter and more broadly framed. What doesn\'t flex is timing: reviewed early, it sharpens focus on value, lowers cost, and reduces rework. Reviewed late, it arrives only after the rework it was meant to prevent has already happened. Six components hold it together: the standards being used, the objectives being targeted, the roles accountable for quality, the deliverables and processes actually under review, the control and management activities planned, and the tools and nonconformance procedures that answer, in advance, what happens the moment something fails a check.',bullets:['Formality scales to the project; timing does not — review the plan early','“Quality planned late is rework scheduled”','Six components: standards, objectives, roles, deliverables, activities, and tools/nonconformance procedures','All six are decided before work begins, not after a defect appears']}};
function Modal({d,close,read}){const[step,setStep]=useState(0);let memory=d.bullets&&step===1;return createPortal(<div className="modal-backdrop" onClick={close}><section className="focus-modal" onClick={e=>e.stopPropagation()}><button className="modal-x" onClick={close}><X/></button>{!memory&&<><img className="modal-illustration" src={A+d.image}/><h3>{d.title}</h3><div className="modal-copy"><p>{d.text}</p></div></>}{memory&&<div className="memory-step"><p className="eyebrow">EXAM-RELEVANT ENABLERS TO REMEMBER</p><ul>{d.bullets.map(x=><li key={x}>{x}</li>)}</ul></div>}{d.bullets&&step===0?<button className="modal-action" onClick={()=>setStep(1)}>Next <ArrowRight/></button>:<button className="modal-action" onClick={()=>{read();close()}}>Mark as read <Check/></button>}</section></div>,document.body)}
const quiz={q:'Scenario: Two similar-sized software projects are each building their quality management plans. Project A finalizes its plan in the first two weeks, before any development work begins. Project B doesn\'t formalize its quality management plan until month four, after a wave of customer-reported defects forces the team to figure out, reactively, how quality issues should actually be handled. What does PMBOK® 8\'s guidance suggest about the likely difference in outcomes between these two projects?',a:['There is no meaningful difference — both projects ultimately produced a quality management plan, so timing does not affect outcomes','Project B benefits more because its plan is based on actual defects rather than assumptions made before development','Project A likely experiences sharper focus on value, lower cost, and fewer schedule overruns from rework because the plan was reviewed early','Formality matters more than timing, so whichever plan is more detailed will produce better outcomes'],good:'Correct. PMBOK® 8 explicitly connects early review of the quality management plan with sharper focus on value, lower cost, and fewer schedule overruns caused by rework.',bad:'Reconsider the timing guidance. PMBOK® 8 is explicit that the quality management plan should be reviewed early so decisions rest on accurate information from the start. Quality planned late is rework scheduled.'};
function Quiz({finish}){const[p,setP]=useState(null);return createPortal(<div className="knowledge-backdrop"><section className="knowledge-modal"><button className="modal-x" onClick={finish}><X/></button><p className="quiz-label"><Target/> MICRO KNOWLEDGE CHECK</p><h3>{quiz.q}</h3><div className="answers vertical">{quiz.a.map((x,i)=><button key={x} onClick={()=>setP(i)} className={p===i?(i===2?'correct':'wrong'):''}><span>{'ABCD'[i]}</span>{x}</button>)}</div>{p!==null&&<><p className={`feedback ${p===2?'good':'bad'}`}>{p===2?quiz.good:quiz.bad}</p><button className="finish-check" onClick={finish}>Finish check <ArrowRight/></button></>}</section></div>,document.body)}
function App(){const[s,setS]=useState(0),[done,setDone]=useState([false,false,false,false,false]),[modal,setModal]=useState(null),[quizOpen,setQuizOpen]=useState(false),[seen,setSeen]=useState([]),[sound,setSound]=useState(true),[outline,setOutline]=useState(false);const mark=i=>setDone(v=>v.map((x,n)=>n===i?true:x));const go=i=>{if(i>=0&&i<5&&(i===0||done[i-1]))setS(i)};const openComp=i=>{setSeen(v=>v.includes(i)?v:[...v,i]);setModal({title:components[i][0],image:components[i][1],text:components[i][2],component:true})};return <div className="app"><header><button className="course" onClick={()=>setOutline(!outline)}><Menu/> Project Management Professional <ChevronDown/></button><div className="dots">{Array.from({length:10},(_,i)=><span key={i} className={i<7?'past':i===7?'current':''}>{i<7&&<Check/>}</span>)}</div><div className="tools"><button onClick={()=>setSound(!sound)}>{sound?<Volume2/>:<VolumeX/>}{sound?'Sound on':'Sound off'}</button><button>Quit</button></div></header><div className="section-label">SECTION {s+1} OF 5</div><nav>{tabs.map((t,i)=><button key={t} onClick={()=>go(i)} disabled={i>0&&!done[i-1]} className={i===s?'active':done[i]?'complete':''}>{done[i]&&<Check/>}{t}</button>)}</nav><main>
{s===0&&<section className="hero"><div><p className="eyebrow">LESSON 4.8.2</p><h1>Plan Quality Processes and Tools</h1><p>An architect doesn't decide, halfway through construction, that the building needs a foundation inspection process. That decision — how the building will be checked, at what stages, against what standard — gets made before the first shovel hits the ground. Decide it late, and any problem the inspection would have caught is now buried under three more floors of work built on top of it.</p><button className="primary" onClick={()=>setModal(modalData.hook)}>Reveal the quality blueprint <ArrowRight/></button></div><img src={A+'01-foundation-hook.png'}/></section>}
{s===1&&<section className="hero"><div><p className="eyebrow">WHAT THIS ENABLER MEANS</p><h2>This isn't a one-size-fits-all document.</h2><p>It's a plan sized to fit exactly what the project in front of you actually needs.</p><button className="primary" onClick={()=>setModal(modalData.fit)}>Reveal the proportional plan <ArrowRight/></button></div><img src={A+'03-proportional-plans.png'}/></section>}
{s===2&&<section className="hero"><div><p className="eyebrow">THE ONE THING THAT DOESN'T FLEX: TIMING</p><h2>Formality can scale up or down depending on the project.</h2><p>One thing about this plan never flexes, no matter how big or small the project is.</p><button className="primary" onClick={()=>setModal(modalData.timing)}>Reveal the timing rule <ArrowRight/></button>{done[2]&&<p className="success"><Check/> Interaction complete — continue when ready.</p>}</div><img src={A+'05-early-vs-late.png'}/></section>}
{s===3&&<section className="components"><p className="eyebrow">SIX COMPONENTS OF THE PLAN</p><h2>Six components make up the quality management plan.</h2><p>Click each to explore.</p><img className="wide-illustration" src={A+'07-six-components.png'}/><div className="component-grid">{components.map((c,i)=><button key={c[0]} onClick={()=>openComp(i)} className={seen.includes(i)?'seen':''}><span>{String(i+1).padStart(2,'0')}</span><strong>{c[0]}</strong><ArrowRight/></button>)}</div>{seen.length===6&&<button className="primary centered" onClick={()=>setModal(modalData.example)}>Open the worked example <ArrowRight/></button>}</section>}
{s===4&&<section className="hero"><div><p className="eyebrow">EXAM LENS</p><h2>Back to the architect one more time — because the inspection process was never optional.</h2><p>It was just a question of when it got decided.</p><button className="primary" onClick={()=>setModal(modalData.exam)}>Reveal the exam lens <ArrowRight/></button></div><img src={A+'15-foundation-complete.png'}/></section>}
</main><footer><button onClick={()=>go(s-1)} disabled={s===0}><ArrowLeft/> Previous</button><button className="continue" onClick={()=>go(s+1)} disabled={!done[s]||s===4}>{s===4?'Complete': 'Continue'} <ArrowRight/></button></footer>{modal&&<Modal d={modal} close={()=>setModal(null)} read={()=>{if(modal.component)return;if(s===2){setQuizOpen(true)}else mark(s)}}/>}{quizOpen&&<Quiz finish={()=>{setQuizOpen(false);mark(2)}}/>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
